version: '3.7'
services:
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - '9999:9999'
    volumes:
      - '.:/var/www/html/'
    command: 'php -S 0.0.0.0:9999 -t public'
